"""Growing tag vocabulary — the "learn tags from recipes" memory.

Every tag the renderer emits is recorded here, namespaced by the part before the first
'/'. The skills read this back (`wk vocab`) before classifying a new item so they reuse
an existing tag instead of coining a near-synonym ('cuisine/japanese' vs 'cuisine/japan'),
which keeps the vocabulary consistent as it grows across hundreds of recipes. Counts are
authoritative after a full `reprocess` pass (page frequency); a single `commit` only
ensures a genuinely new tag becomes visible, so re-committing a page never inflates counts.
"""
from __future__ import annotations

import json
from pathlib import Path


def _split(tag: str) -> tuple[str, str]:
    """('cuisine/japanese') -> ('cuisine', 'japanese'); a bare tag -> ('_', tag)."""
    ns, sep, leaf = str(tag).partition("/")
    return (ns, leaf) if sep else ("_", ns)


class Vocabulary:
    """JSON-backed tag registry at <state_dir>/known_tags.json:
    {namespace: {leaf: count}}."""

    def __init__(self, state_dir):
        self.path = Path(state_dir) / "known_tags.json"

    # ---- io ---------------------------------------------------------------- #
    def _load(self) -> dict:
        if self.path.is_file():
            try:
                return json.loads(self.path.read_text())
            except (ValueError, OSError):
                return {}
        return {}

    def _save(self, data: dict) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False))

    # ---- update ------------------------------------------------------------ #
    def record(self, tags) -> None:
        """Incremental: ensure each tag is present (new -> count 1). Does NOT bump
        existing counts, so re-committing the same page is idempotent."""
        data = self._load()
        changed = False
        for t in tags or []:
            ns, leaf = _split(t)
            bucket = data.setdefault(ns, {})
            if leaf not in bucket:
                bucket[leaf] = 1
                changed = True
        if changed:
            self._save(data)

    def rebuild(self, tag_lists) -> dict:
        """Authoritative recompute over every page's tag list — counts become page
        frequency. Used by the full `reprocess` pass."""
        data: dict = {}
        for tags in tag_lists:
            for t in tags or []:
                ns, leaf = _split(t)
                bucket = data.setdefault(ns, {})
                bucket[leaf] = bucket.get(leaf, 0) + 1
        self._save(data)
        return data

    # ---- read -------------------------------------------------------------- #
    def data(self) -> dict:
        return self._load()

    def known(self) -> set:
        out = set()
        for ns, bucket in self._load().items():
            for leaf in bucket:
                out.add(leaf if ns == "_" else f"{ns}/{leaf}")
        return out

    def render_dashboard(self) -> str:
        """A human-readable vault page listing the whole vocabulary by namespace."""
        data = self._load()
        total = sum(sum(b.values()) for b in data.values())
        lines = [
            "# Tag vocabulary",
            "",
            f"> Auto-generated by khenrix-wiki-sync — {total} tag uses across "
            f"{len(data)} namespaces. Consult this before tagging a new item and reuse "
            "an existing tag when it fits.",
            "",
        ]
        for ns in sorted(data):
            bucket = data[ns]
            heading = "(bare)" if ns == "_" else ns
            lines.append(f"## {heading}")
            for leaf in sorted(bucket, key=lambda k: (-bucket[k], k)):
                tag = leaf if ns == "_" else f"{ns}/{leaf}"
                lines.append(f"- `{tag}` — {bucket[leaf]}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"
